PHRASES = [
    # --- EUROPA ---
    {
        "phrase": "C’est magnifique, on va prendre un verre en terrasse après le travail ce soir ?",
        "language": "Francès",
        "country": "França",
        "catalan_translation": "És magnífic, anem a prendre una copa a la terrassa després de la feina aquest vespre?",
        "flag": "🇫🇷",
        "hint": "Un país on la cultura de la 'terrasse' i la gastronomia defineixen la vida social",
        "population": "68 milions", "continent": "Europa", "iso_code": "fr",
    },
    {
        "phrase": "Buon giorno a tutti! Che bella giornata per bere un vero espresso in piazza.",
        "language": "Italià",
        "country": "Itàlia",
        "catalan_translation": "Bon dia a tothom! Quin dia més bonic per beure un cafè exprés de veritat a la plaça.",
        "flag": "🇮🇹",
        "hint": "Aquí el concepte de 'la bella figura' és una autèntica filosofia de vida estètica",
        "population": "59 milions", "continent": "Europa", "iso_code": "it",
    },
    {
        "phrase": "¡Olé! Mañana nos vamos de cañas y nos quedamos de sobremesa durante muchas horas.",
        "language": "Castellà",
        "country": "Espanya",
        "catalan_translation": "Bravo! Demà anem a fer unes canyes i ens quedem de sobretaula durant moltes hores.",
        "flag": "🇪🇸",
        "hint": "On les reunions familiars acaben hores després d'haver dinat xerrant sense cap pressa",
        "population": "47 milions", "continent": "Europa", "iso_code": "es",
    },
    {
        "phrase": "Entschuldigung, wissen Sie, ob der Zug heute pünktlich am Berliner Hauptbahnhof ankommen wird?",
        "language": "Alemany",
        "country": "Alemanya",
        "catalan_translation": "Disculpi, sap si el tren arribarà puntual avui a l'estació central de Berlín?",
        "flag": "🇩🇪",
        "hint": "Un lloc on la puntualitat és una norma social gairebé sagrada i molt respectada",
        "population": "84 milions", "continent": "Europa", "iso_code": "de",
    },
    {
        "phrase": "I'm terribly sorry to bother you, but could you please show me the way?",
        "language": "Anglès",
        "country": "Anglaterra",
        "catalan_translation": "Em sap greu molestar-lo, però podria si us plau mostrar-me el camí?",
        "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        "hint": "Un país on demanar disculpes per absolutament tot és la base de la cortesia",
        "population": "57 milions", "continent": "Europa", "iso_code": "gb",
    },
    {
        "phrase": "Tack så mycket! Ska vi ta una fika med kaffe och bullar idag?",
        "language": "Suec",
        "country": "Suècia",
        "catalan_translation": "Moltes gràcies! Fem una pausa per al cafè amb brioixos avui?",
        "flag": "🇸🇪",
        "hint": "Practiquen el 'lagom', que significa ni massa ni poc, tot just l'equilibri perfecte",
        "population": "10 milions", "continent": "Europa", "iso_code": "se",
    },

    # --- AMÈRICA (Diferenciant països per argot) ---
    {
        "phrase": "¡Hola, parce! ¿Qué más? ¿Cómo va todo por allá en la tierrita hoy?",
        "language": "Castellà (Colòmbia)",
        "country": "Colòmbia",
        "catalan_translation": "Hola, amic! Com va tot per allà a la terroneta avui?",
        "flag": "🇨🇴",
        "hint": "Un lloc on tothom et dirà 'parce' i on el millor cafè neix a les muntanyes",
        "population": "51 milions", "continent": "Amèrica del Sud", "iso_code": "co",
    },
    {
        "phrase": "Che, ¿viste lo que pasó ayer en la cancha? Fue un partido realmente increíble.",
        "language": "Castellà (Argentina)",
        "country": "Argentina",
        "catalan_translation": "Escolta, vas veure què va passar ahir al camp? Va ser un partit increïble.",
        "flag": "🇦🇷",
        "hint": "En aquest país el 'voseo' és la norma i el mate és l'eix social",
        "population": "46 milions", "continent": "Amèrica del Sud", "iso_code": "ar",
    },
    {
        "phrase": "¡Órale güey! No te pases de lanza con esa broma tan pesada que hiciste.",
        "language": "Castellà (Mèxic)",
        "country": "Mèxic",
        "catalan_translation": "Vinga, noi! No et passis de la ratlla amb aquesta broma tan pesada que has fet.",
        "flag": "🇲🇽",
        "hint": "Si et diuen que el menjar pica 'poquito', prepara't per a una experiència volcànica",
        "population": "130 milions", "continent": "Amèrica del Nord", "iso_code": "mx",
    },
    {
        "phrase": "Pura vida, mae! Todo bien por aquí, disfrutando de la selva y la playa.",
        "language": "Castellà (Costa Rica)",
        "country": "Costa Rica",
        "catalan_translation": "Tot va genial, noi! Tot bé per aquí, gaudint de la selva i la platja.",
        "flag": "🇨🇷",
        "hint": "Els seus habitants s'anomenen 'ticos' i viuen en un país que no té exèrcit",
        "population": "5 milions", "continent": "Amèrica Central", "iso_code": "cr",
    },
    {
        "phrase": "¡Oye, po! La wea está súper fome, mejor vamos a buscar algo más entretenido.",
        "language": "Castellà (Xile)",
        "country": "Xile",
        "catalan_translation": "Escolta! Això és molt avorrit, millor anem a buscar alguna cosa més divertida.",
        "flag": "🇨🇱",
        "hint": "Utilitzen la paraula 'wea' per a tot i és el país més llarg del món",
        "population": "19 milions", "continent": "Amèrica del Sud", "iso_code": "cl",
    },
    {
        "phrase": "Oi, tudo bem? Uai, você não sabia que eu vinha visitar você hoje cedo?",
        "language": "Portuguès (Brasil)",
        "country": "Brasil",
        "catalan_translation": "Hola, tot bé? Carai, no sabies que venia a visitar-te avui d'hora?",
        "flag": "🇧🇷",
        "hint": "A la regió de Minas Gerais fan servir 'uai' per expressar qualsevol tipus de sorpresa",
        "population": "215 milions", "continent": "Amèrica del Sud", "iso_code": "br",
    },
    {
        "phrase": "¡Ya tu sabes, asere! Vamos a pasar un rato bien chévere con la música.",
        "language": "Castellà (Cuba)",
        "country": "Cuba",
        "catalan_translation": "Ja ho saps, col·lega! Anem a passar una estona ben xula amb la música.",
        "flag": "🇨🇺",
        "hint": "Et saludaran amb un 'asere, ¿qué bolá?' en aquesta illa del Carib",
        "population": "11 milions", "continent": "Amèrica Central", "iso_code": "cu",
    },

    # --- ÀSIA I OCEANIA ---
    {
        "phrase": "Kon'nichiwa! O-genki desu ka? Nihon no sakura wa haru ni totemo kirei desu.",
        "language": "Japonès",
        "country": "Japó",
        "catalan_translation": "Hola! Com estàs? Els cirerers del Japó a la primavera són molt bonics.",
        "flag": "🇯🇵",
        "hint": "Una societat que valora el silenci, l'ordre i l'harmonia grupal per sobre de tot",
        "population": "125 milions", "continent": "Àsia", "iso_code": "jp",
    },
    {
        "phrase": "Anyoung haseyo! Kimchi jinjja masisseoyo, kamsahamnida por este delicioso banquete que habéis preparado.",
        "language": "Coreà",
        "country": "Corea del Sud",
        "catalan_translation": "Hola! El kimchi és realment bo, gràcies per aquest banquet deliciós que heu preparat.",
        "flag": "🇰🇷",
        "hint": "L'edat i l'estatus determinen estrictament com has de conjugar els verbs en parlar",
        "population": "52 milions", "continent": "Àsia", "iso_code": "kr",
    },
    {
        "phrase": "Nǐ hǎo! Nǐ chī fàn le ma? Zhège dìfāng hěn piàoliang yeyi.",
        "language": "Xinès mandarí",
        "country": "Xina",
        "catalan_translation": "Hola! Ja has menjat? Aquest lloc és realment molt bonic.",
        "flag": "🇨🇳",
        "hint": "Preguntar 'si ja has menjat' és la manera tradicional de saludar els amics propers",
        "population": "1.400 milions", "continent": "Àsia", "iso_code": "cn",
    },
    {
        "phrase": "G'day mate! Are you coming to the barbie this afternoon at the beach?",
        "language": "Anglès (australià)",
        "country": "Austràlia",
        "catalan_translation": "Bon dia, amic! Vindràs a la barbacoa aquesta tarda a la platja?",
        "flag": "🇦🇺",
        "hint": "Són famosos per escurçar paraules: 'barbie' (barbacoa), 'brekkie' (esmorzar) o 'straya' (el seu país)",
        "population": "26 milions", "continent": "Oceania", "iso_code": "au",
    },
    {
        "phrase": "Sawadee krap! Yin dee tee dai roo juk. Thailand suay mak mak.",
        "language": "Tai",
        "country": "Tailàndia",
        "catalan_translation": "Hola! Encantat de conèixer-te. Tailàndia és molt i molt maca.",
        "flag": "🇹🇭",
        "hint": "Conegut com 'el país del somriure' per l'amabilitat extrema de la seva gent",
        "population": "71 milions", "continent": "Àsia", "iso_code": "th",
    },

    # --- ÀFRICA I ORIENT MITJÀ ---
    {
        "phrase": "Shukran! El chai con menta está muy rico, muchas gracias por vuestra hospitalidad.",
        "language": "Àrab",
        "country": "Marroc",
        "catalan_translation": "Gràcies! El te amb menta és molt bo, moltes gràcies per la vostra hospitalitat.",
        "flag": "🇲🇦",
        "hint": "L'hospitalitat es demostra servint el te des de molta alçada per crear bromera",
        "population": "37 milions", "continent": "Àfrica", "iso_code": "ma",
    },
    {
        "phrase": "Ubuntu! Soy porque nosotros somos, trabajemos juntos por el futuro de nuestra nación.",
        "language": "Zulu / Anglès",
        "country": "Sud-àfrica",
        "catalan_translation": "Soc perquè nosaltres som, treballem junts pel futur de la nostra nació.",
        "flag": "🇿🇦",
        "hint": "L'anomenada 'Nació de l'Arc de Sant Martí' té fins a 11 llengües oficials",
        "population": "60 milions", "continent": "Àfrica", "iso_code": "za",
    },
    {
        "phrase": "Hakuna matata! Todo va a salir bien, no te preocupes por los problemas.",
        "language": "Swahili",
        "country": "Kènia",
        "catalan_translation": "Cap problema! Tot sortirà bé, no et preocupis pels problemes.",
        "flag": "🇰🇪",
        "hint": "La frase 'hakuna matata' és realment part del vocabulari quotidià en aquest país",
        "population": "55 milions", "continent": "Àfrica", "iso_code": "ke",
    },
    {
        "phrase": "Selam! Dehna nesh? Ethiopia betam konjo natch. Enes tegnen.",
        "language": "Amhàric",
        "country": "Etiòpia",
        "catalan_translation": "Hola! Com estàs? Etiòpia és molt bonica. Som-hi.",
        "flag": "🇪🇹",
        "hint": "L'únic país africà que mai va ser colonitzat i té el seu propi calendari",
        "population": "123 milions", "continent": "Àfrica", "iso_code": "et",
    },

    # --- ALTRES REGIONS ---
    {
        "phrase": "Privyet! Kak dela? Segodnya ochen' kholodno zdes' v gorode, pravda?",
        "language": "Rus",
        "country": "Rússia",
        "catalan_translation": "Hola! Com va? Avui fa molt de fred aquí a la ciutat, oi?",
        "flag": "🇷🇺",
        "hint": "El país més gran del món, on la gent rarament somriu als desconeguts pel carrer",
        "population": "144 milions", "continent": "Europa/Àsia", "iso_code": "ru",
    },
    {
        "phrase": "Merhabalar! Nasilsiniz? Turkiye cok guzel bir ulke, her sey harika.",
        "language": "Turc",
        "country": "Turquia",
        "catalan_translation": "Hola! Com esteu? Turquia és un país molt bonic, tot és fantàstic.",
        "flag": "🇹🇷",
        "hint": "Un pont geogràfic i cultural entre Europa i Àsia dividit pel Bòsfor",
        "population": "85 milions", "continent": "Àsia/Europa", "iso_code": "tr",
    },
]

# Accepted alternative answers for countries
# All valid country names accepted (normalized: lowercase, no accents)
VALID_COUNTRIES = {
    "afganistan", "albania", "alemanya", "germany", "deutschland", "alemania",
    "andorra", "angola", "arabia saudita", "saudi arabia", "arabia saudi", "arabia",
    "argelia", "algeria", "argentina", "armenia", "australia", "austria",
    "azerbaijan", "bahames", "bahrain", "bangladesh", "belgica", "belgium", "belgique",
    "belize", "benin", "bielorusia", "bielorrusia", "belarus", "bolivia",
    "bosnia", "botswana", "brasil", "brazil", "brunei", "bulgaria", "burkina faso",
    "burundi", "butan", "cap verd", "cambodja", "camerun", "canada", "canada",
    "colombia", "comores", "congo", "corea", "corea del sud", "corea del norte",
    "south korea", "north korea", "korea", "costa rica", "croacia", "cuba",
    "xipre", "cyprus", "xina", "china", "xile", "chile", "dinamarca", "denmark",
    "djibouti", "dominica", "equador", "ecuador", "egipte", "egypt", "el salvador",
    "emirats arabs units", "uae", "eritrea", "eslovenia", "eslovaquia", "slovakia",
    "slovenia", "espanya", "spain", "espana", "estats units", "united states", "usa",
    "america", "estonia", "etiopia", "ethiopia", "filipines", "philippines",
    "finlandia", "finland", "franca", "france", "franc", "gabon", "gambia",
    "georgia", "ghana", "grecia", "greece", "groenlandia", "guatemala", "guinea",
    "guyana", "haiti", "honduras", "hongria", "hungary", "india", "indonesia",
    "irak", "iraq", "iran", "irlanda", "ireland", "islandia", "iceland",
    "israel", "italia", "italy", "jamaica", "japo", "japan", "japon", "jordania",
    "jordan", "kazakhstan", "kenia", "kenya", "kirguistan", "kiribati", "kuwait",
    "laos", "letonia", "latvia", "liban", "lebanon", "liberia", "libia", "libya",
    "liechtenstein", "lituania", "lithuania", "luxemburg", "luxemburgo",
    "madagascar", "malawi", "malasia", "malaysia", "maldives", "mali", "malta",
    "marroc", "morocco", "marruecos", "maurici", "mauritania", "mexic", "mexico",
    "micronesia", "moldavia", "moldova", "monaco", "mongolia", "montenegro",
    "mozambic", "mozambique", "namibia", "nepal", "nicaragua", "niger", "nigeria",
    "noruega", "norway", "nova zelanda", "new zealand", "oman", "paisos baixos",
    "holanda", "holland", "netherlands", "pakistan", "palau", "palestina",
    "panama", "papua nova guinea", "paraguai", "paraguay", "peru", "polonia",
    "poland", "portugal", "qatar", "romania", "rumania", "russia", "rusia",
    "ruanda", "rwanda", "samoa", "san marino", "senegal", "serbia", "sierra leona",
    "singapur", "singapore", "siria", "syria", "somalia", "sri lanka",
    "sud africa", "sudafrica", "south africa", "sudan", "suecia", "sweden",
    "suissa", "switzerland", "surinam", "tailandia", "thailand", "taiwan",
    "tajikistan", "tanzania", "timor oriental", "togo", "tonga", "trinidad",
    "tunis", "tunisia", "turquia", "turkey", "turkmenistan", "tuvalu", "ucraïna",
    "ucraina", "ukraine", "uganda", "uruguai", "uruguay", "uzbekistan", "vanuatu",
    "venezuela", "vietnam", "viet nam", "iemen", "yemen", "zambia", "zimbabue",
    "zimbabwe", "anglaterra", "england", "uk", "gran bretanya", "united kingdom",
    "reino unido", "escòcia", "scotland", "galles", "wales", "irlanda del nord",
    "northern ireland", "costa d'ivori", "ivory coast", "burkina", "guinea bissau",
    "guinea equatorial", "equatorial guinea", "sao tome", "comoros", "eswatini",
    "suazilandia", "lesotho", "djibouti", "eritrea", "sud-africa", "sudafrica",
    "corea del sud", "corea sud", "corea norte", "republica dominicana",
    "dominican republic", "republica checa", "czech republic", "txequia",
    "republica centreafricana", "central african republic",
}

ACCEPTED_ANSWERS = {
    "França": ["franca", "france", "franc", "francesa"],
    "Itàlia": ["italia", "italy", "italià"],
    "Espanya": ["espanya", "spain", "españa", "espanyol"],
    "Alemanya": ["alemanya", "germany", "deutschland", "alemania"],
    "Anglaterra": ["anglaterra", "england", "uk", "gran bretanya", "gran bretanya", "united kingdom", "reino unido"],
    "Països Baixos": ["paisos baixos", "holanda", "holland", "netherlands", "paises bajos"],
    "Japó": ["japo", "japan", "japon"],
    "Portugal": ["portugal"],
    "Noruega": ["noruega", "norway"],
    "Grècia": ["grecia", "greece"],
    "Israel": ["israel"],
    "Costa Rica": ["costa rica"],
    "Sud-àfrica": ["sud africa", "sudafrica", "south africa", "sudàfrica"],
    "Aràbia Saudita": ["arabia saudita", "saudi arabia", "arabia saudi", "aràbia"],
    "Mèxic": ["mexic", "mexico"],
    "Rússia": ["russia", "russia", "rusia"],
    "Xina": ["xina", "china"],
    "Índia": ["india", "índia"],
    "Brasil": ["brasil", "brazil"],
    "Austràlia": ["australia", "austràlia"],
    "Polònia": ["polonia", "poland"],
    "Turquia": ["turquia", "turkey"],
    "Marroc": ["marroc", "morocco", "marruecos"],
    "Corea del Sud": ["corea del sud", "corea", "south korea", "korea"],
    "Suècia": ["suecia", "sweden", "suècia"],
    "Argentina": ["argentina"],
    "Kènia": ["kenia", "kenya"],
}
